# Kentucky School Initial Data Review

Investigate Kentucky public school education data to explore the relationship between student enrollment, chronic absenteeism, and dropout rate.

Libraries and Parameters

In [530]:
import pandas as pd
import matplotlib.pyplot as plt

## KY School Data (2023-2025)

In [531]:
enrollment_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Student_Enrollment.csv")
enrollment_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Student_Enrollment.csv")

absenteeism_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Chronic_Absenteeism.csv")
absenteeism_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Chronic_Absenteeism.csv")

dropout_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Dropout_Rate.csv")
dropout_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Dropout_Rate.csv")

ky_regions_df = pd.read_csv("../Dataset/Ky_County_Polygons_WM.csv")

enrollment_df = pd.concat([enrollment_2023_2024_df, enrollment_2024_2025_df], ignore_index=True)
chronic_absenteeism_df = pd.concat([absenteeism_2023_2024_df, absenteeism_2024_2025_df], ignore_index=True)
dropout_rate_df = pd.concat([dropout_2023_2024_df, dropout_2024_2025_df], ignore_index=True)

## Initial Dataset Review

In [532]:
ky_regions_df

,OBJECTID,NAME,FIPS_ID,NAME2,ADDNAME,SEAT,SEAT2,FORM_YR,PARENTCO,FIPS_NO,...,CONTACT,LAST_UPDT,XY_SOURCE,XY_ISSUES,ATT_SOURCE,ATT_ISSUES,COMMENTS,KYTC_District_Num,Shape__Area,Shape__Length
0,1,ADAIR,21001,Adair,LAKE CUMBERLAND,Columbia,COLUMBIA,1802,Green,1,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,8,1.682320e+09,176916.9036
1,2,ALLEN,21003,Allen,BARREN RIVER,Scottsville,SCOTTSVILLE,1815,"Barren, Warren",3,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,3,1.422340e+09,212158.8170
2,3,ANDERSON,21005,Anderson,BLUEGRASS,Lawrenceburg,LAWRENCEBURG,1827,"Franklin, Mercer, Washington",5,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,7,8.534822e+08,187271.1613
3,4,BALLARD,21007,Ballard,PURCHASE,Wickliffe,WICKLIFFE,1842,"Hickman, McCracken",7,...,KIM ANNESS,7/23/2015 0:00,"OHIO V. KENTUCKY, 444 U.S. 335 (1980)",NaN,SECRETARY OF STATE,NaN,BOUNDARY UPDATED TO MATCH SUPREME COURT CASE R...,1,1.116332e+09,169743.5539
4,5,BARREN,21009,Barren,BARREN RIVER,Glasgow,GLASGOW,1799,"Green, Warren",9,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,3,2.032351e+09,235199.6736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,WAYNE,21231,Wayne,LAKE CUMBERLAND,Monticello,MONTICELLO,1801,"Cumberland, Pulaski",231,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,8,1.959573e+09,214715.8624
116,117,WEBSTER,21233,Webster,GREEN RIVER,Dixon,DIXON,1860,"Henderson, Hopkins, Union",233,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,2,1.384222e+09,197143.2294
117,118,WHITLEY,21235,Whitley,CUMBERLAND VALLEY,Williamsburg,WILLIAMSBURG,1818,Knox,235,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,11,1.799520e+09,238465.4839
118,119,WOLFE,21237,Wolfe,KENTUCKY RIVER,Campton,CAMPTON,1860,"Breathitt, Morgan, Owsley, Powell",237,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,10,9.241010e+08,184878.7025
119,120,WOODFORD,21239,Woodford,BLUEGRASS,Versailles,VERSAILLES,1789,Fayette,239,...,"TRANSPORTATION SYSTEMS BRANCH MANAGER, DIVISIO...",7/1/1993 0:00,BOUNDARY DIGITIZED FROM USGS 7.5 MINUTE TOPOGR...,NaN,SECRETARY OF STATE,NaN,NaN,7,8.032135e+08,187168.7892

In [533]:
enrollment_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,...,Grade 4,Grade 5,Grade 6,Grade 7,Grade 8,Grade 9,Grade 10,Grade 11,Grade 12,Grade 14
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"49,321","49,728","46,144","49,278","50,090","56,075","54,149","50,192","47,786",653.0
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"23,912","24,119","22,146","23,926","24,063","27,061","26,353","24,607","23,210",217.0
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"25,409","25,609","23,998","25,352","26,027","29,014","27,796","25,585","24,576",436.0
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"5,279","5,381","4,763","5,474","5,541","6,605","6,294","5,566","5,059",103.0
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,84,68,59,59,72,79,66,78,68,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46223,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,1,3,6,11,NaN
46224,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,1,0,2,0,NaN
46225,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,1,1,0,0,3,2,4,NaN
46226,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,0,1,1,0,NaN
46227,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,0,0,1,0,NaN

In [534]:
chronic_absenteeism_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Grade,Demographic,Suppressed,Chronically Absent Students,Students Enrolled 10 or More Days,Chronic Absenteeism Rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,All Students,No,"186,415","664,910",28
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Female,No,"91,571","321,064",28.5
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Male,No,"94,844","343,846",27.6
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,African American,No,"25,283","73,438",34.4
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,American Indian or Alaska Native,No,290,962,30.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543271,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Foster Care,Yes,*,*,*
543272,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Gifted and Talented,Yes,*,*,*
543273,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Homeless,Yes,*,*,*
543274,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Migrant,Yes,*,*,*
543275,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Military Dependent,Yes,*,*,*

In [535]:
dropout_rate_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Demographic,Suppressed,Dropout Rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Students,N,1.3
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Female,N,1.1
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Male,N,1.5
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,African American,N,2.2
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,American Indian or Alaska Native,N,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24529,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Student without Disabilities (IEP),N,0
24530,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,English Learner,Y,*
24531,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Non English Learner,N,0
24532,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Homeless,NaN,
24533,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Migrant,NaN,

## Analyzing the Data

In [536]:
enrollment_df.shape

(46228, 30)

In [537]:
enrollment_df.columns.tolist()

['School Year',
 'County Number',
 'County Name',
 'District Number',
 'District Name',
 'School Number',
 'School Name',
 'School Code',
 'State School Id',
 'NCES ID',
 'CO-OP',
 'CO-OP Code',
 'School Type',
 'Demographic',
 'All Grades',
 'Preschool',
 'K',
 'Grade 1',
 'Grade 2',
 'Grade 3',
 'Grade 4',
 'Grade 5',
 'Grade 6',
 'Grade 7',
 'Grade 8',
 'Grade 9',
 'Grade 10',
 'Grade 11',
 'Grade 12',
 'Grade 14']

In [538]:
enrollment_df.dtypes

School Year          int64
County Number      float64
County Name         object
District Number      int64
District Name       object
School Number      float64
School Name         object
School Code          int64
State School Id    float64
NCES ID            float64
CO-OP               object
CO-OP Code         float64
School Type         object
Demographic         object
All Grades          object
Preschool           object
K                   object
Grade 1             object
Grade 2             object
Grade 3             object
Grade 4             object
Grade 5             object
Grade 6             object
Grade 7             object
Grade 8             object
Grade 9             object
Grade 10            object
Grade 11            object
Grade 12            object
Grade 14           float64
dtype: object

In [539]:
enrollment_df.duplicated().sum()

np.int64(0)

In [540]:
chronic_absenteeism_df.shape

(543276, 19)

In [541]:
chronic_absenteeism_df.columns.tolist()

['School Year',
 'County Number',
 'County Name',
 'District Number',
 'District Name',
 'School Number',
 'School Name',
 'School Code',
 'State School Id',
 'NCES ID',
 'CO-OP',
 'CO-OP Code',
 'School Type',
 'Grade',
 'Demographic',
 'Suppressed',
 'Chronically Absent Students',
 'Students Enrolled 10 or More Days',
 'Chronic Absenteeism Rate']

In [542]:
chronic_absenteeism_df.dtypes

School Year                            int64
County Number                        float64
County Name                           object
District Number                        int64
District Name                         object
School Number                        float64
School Name                           object
School Code                            int64
State School Id                      float64
NCES ID                              float64
CO-OP                                 object
CO-OP Code                           float64
School Type                           object
Grade                                 object
Demographic                           object
Suppressed                            object
Chronically Absent Students           object
Students Enrolled 10 or More Days     object
Chronic Absenteeism Rate              object
dtype: object

In [543]:
chronic_absenteeism_df.isna().sum()

School Year                              0
County Number                          541
County Name                            541
District Number                          0
District Name                            0
School Number                        78028
School Name                              0
School Code                              0
State School Id                      78028
NCES ID                              28204
CO-OP                                 2190
CO-OP Code                            2190
School Type                          78028
Grade                                    0
Demographic                              0
Suppressed                               0
Chronically Absent Students              0
Students Enrolled 10 or More Days        0
Chronic Absenteeism Rate                 0
dtype: int64

## Data Cleanup

In [544]:
ky_regions_df = ky_regions_df[['NAME', 'REGION']]
ky_regions_df = ky_regions_df.rename(columns={'NAME': 'county', 'REGION': 'region'})
ky_regions_df

       county                region
0       ADAIR  SOUTH CENTRAL REGION
1       ALLEN  SOUTH CENTRAL REGION
2    ANDERSON      BLUEGRASS REGION
3     BALLARD        WESTERN REGION
4      BARREN  SOUTH CENTRAL REGION
..        ...                   ...
115     WAYNE  SOUTH CENTRAL REGION
116   WEBSTER        WESTERN REGION
117   WHITLEY           EAST REGION
118     WOLFE           EAST REGION
119  WOODFORD      BLUEGRASS REGION

[120 rows x 2 columns]

In [545]:
enrollment_df = enrollment_df.rename(columns={
    'School Year': 'school_year',
    'County Number': 'county_number',
    'County Name': 'county_name',
    'District Number': 'district_number',
    'District Name': 'district_name',
    'School Number': 'school_number',
    'School Name': 'school_name',
    'School Code': 'school_code',
    'State School Id': 'state_school_id',
    'NCES ID': 'nces_id',
    'CO-OP': 'co_op',
    'CO-OP Code': 'co_op_code',
    'School Type': 'school_type',
    'Demographic': 'demographic',
    'All Grades': 'all_grades',
    'Preschool': 'grade_preschool',
    'K': 'grade_k',
    'Grade 1': 'grade_1',
    'Grade 2': 'grade_2',
    'Grade 3': 'grade_3',
    'Grade 4': 'grade_4',
    'Grade 5': 'grade_5',
    'Grade 6': 'grade_6',
    'Grade 7': 'grade_7',
    'Grade 8': 'grade_8',
    'Grade 9': 'grade_9',
    'Grade 10': 'grade_10',
    'Grade 11': 'grade_11',
    'Grade 12': 'grade_12',
    'Grade 14': 'grade_14'
})

In [546]:
chronic_absenteeism_df = chronic_absenteeism_df.rename(columns={
    'School Year': 'school_year',
    'County Number': 'county_number',
    'County Name': 'county_name',
    'District Number': 'district_number',
    'District Name': 'district_name',
    'School Number': 'school_number',
    'School Name': 'school_name',
    'School Code': 'school_code',
    'State School Id': 'state_school_id',
    'NCES ID': 'nces_id',
    'CO-OP': 'co_op',
    'CO-OP Code': 'co_op_code',
    'School Type': 'school_type',
    'Grade': 'grade',
    'Demographic': 'demographic',
    'Suppressed': 'suppressed',
    'Chronically Absent Students': 'chronically_absent_students',
    'Students Enrolled 10 or More Days': 'students_enrolled_10_or_more_days',
    'Chronic Absenteeism Rate': 'chronic_absenteeism_rate'
})

chronic_absenteeism_df.head()

,school_year,county_number,county_name,district_number,district_name,school_number,school_name,school_code,state_school_id,nces_id,co_op,co_op_code,school_type,grade,demographic,suppressed,chronically_absent_students,students_enrolled_10_or_more_days,chronic_absenteeism_rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,All Students,No,"186,415","664,910",28
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Female,No,"91,571","321,064",28.5
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Male,No,"94,844","343,846",27.6
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,African American,No,"25,283","73,438",34.4
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,American Indian or Alaska Native,No,290,962,30.1

In [547]:
dropout_rate_df = dropout_rate_df.rename(columns={
    'School Year': 'school_year',
    'County Number': 'county_number',
    'County Name': 'county_name',
    'District Number': 'district_number',
    'District Name': 'district_name',
    'School Number': 'school_number',
    'School Name': 'school_name',
    'School Code': 'school_code',
    'State School Id': 'state_school_id',
    'NCES ID': 'nces_id',
    'CO-OP': 'co_op',
    'CO-OP Code': 'co_op_code',
    'School Type': 'school_type',
    'Demographic': 'demographic',
    'Suppressed': 'suppressed',
    'Dropout Rate': 'dropout_rate',
})


dropout_rate_df.head()

,school_year,county_number,county_name,district_number,district_name,school_number,school_name,school_code,state_school_id,nces_id,co_op,co_op_code,school_type,demographic,suppressed,dropout_rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Students,N,1.3
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Female,N,1.1
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Male,N,1.5
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,African American,N,2.2
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,American Indian or Alaska Native,N,2.2

## Table DF Creation

In [548]:

ky_regions_df.head()

     county                region
0     ADAIR  SOUTH CENTRAL REGION
1     ALLEN  SOUTH CENTRAL REGION
2  ANDERSON      BLUEGRASS REGION
3   BALLARD        WESTERN REGION
4    BARREN  SOUTH CENTRAL REGION

In [549]:
enrollment_df.columns.tolist()

['school_year',
 'county_number',
 'county_name',
 'district_number',
 'district_name',
 'school_number',
 'school_name',
 'school_code',
 'state_school_id',
 'nces_id',
 'co_op',
 'co_op_code',
 'school_type',
 'demographic',
 'all_grades',
 'grade_preschool',
 'grade_k',
 'grade_1',
 'grade_2',
 'grade_3',
 'grade_4',
 'grade_5',
 'grade_6',
 'grade_7',
 'grade_8',
 'grade_9',
 'grade_10',
 'grade_11',
 'grade_12',
 'grade_14']

In [550]:
ky_district_df = (enrollment_df[['district_number','district_name','county_number','county_name']])
ky_district_df.head()

   district_number  district_name  county_number county_name
0              999  All Districts            NaN         NaN
1              999  All Districts            NaN         NaN
2              999  All Districts            NaN         NaN
3              999  All Districts            NaN         NaN
4              999  All Districts            NaN         NaN

In [551]:
#  school_code VARCHAR(10) PRIMARY KEY,      'school_code',
#  school_number CHAR(3),                    'school_number',
#  school_name VARCHAR(150) NOT NULL,        'school_name',
#  state_school_id VARCHAR(20),              'state_school_id',
#  nces_id VARCHAR(20),                      'nces_id',
#  co_op VARCHAR(100),                       'co_op',
#  co_op_code VARCHAR(20),                   'co_op_code',
#  school_type VARCHAR(50),                  'school_type',
#  district_number CHAR(3) NOT NULL,         'district_number',
#  CONSTRAINT fk_school_district FOREIGN KEY (district_number) REFERENCES district(district_number)


ky_school_detail = (enrollment_df[['school_code','school_number','school_name','state_school_id','nces_id','co_op','co_op_code','school_type','district_number']])
ky_school_detail.head()

,school_code,school_number,school_name,state_school_id,nces_id,co_op,co_op_code,school_type,district_number
0,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
1,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
2,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
3,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
4,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999

In [552]:

# enrollment_id BIGINT AUTO_INCREMENT PRIMARY KEY,
#  school_year CHAR(8) NOT NULL, 'school_year',
#  school_code VARCHAR(10) NOT NULL, 'school_code',
#  demographic VARCHAR(50) NOT NULL, 'demographic',
#  enrollment_total INT NOT NULL, 'all_grades',
#  grade_level VARCHAR(20) NOT NULL,


ky_school_detail = (enrollment_df[['school_code','school_number','school_name','state_school_id','nces_id','co_op','co_op_code','school_type','district_number']])
ky_school_detail.head()

,school_code,school_number,school_name,state_school_id,nces_id,co_op,co_op_code,school_type,district_number
0,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
1,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
2,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
3,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999
4,999000,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,999

In [553]:
ky_school_enrollment_df = pd.melt(
    enrollment_df,
    id_vars = ['school_year','school_code','demographic'], 
    value_vars = ['grade_preschool', 'grade_k', 'grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6', 'grade_7', 'grade_8', 'grade_9', 'grade_10', 'grade_11', 'grade_12', 'grade_14'],
    var_name = 'grade_level',
    value_name = 'enrollment'
                 )

ky_school_enrollment_df.head()

,school_year,school_code,demographic,grade_level,enrollment
0,20232024,999000,All Students,grade_preschool,"31,467"
1,20232024,999000,Female,grade_preschool,"13,950"
2,20232024,999000,Male,grade_preschool,"17,517"
3,20232024,999000,African American,grade_preschool,"3,477"
4,20232024,999000,American Indian or Alaska Native,grade_preschool,34

In [554]:
#   'School Year': 'school_year',
#     'County Number': 'county_number',
#     'County Name': 'county_name',
#     'District Number': 'district_number',
#     'District Name': 'district_name',
#     'School Number': 'school_number',
#     'School Name': 'school_name',
#     'School Code': 'school_code',
#     'State School Id': 'state_school_id',
#     'NCES ID': 'nces_id',
#     'CO-OP': 'co_op',
#     'CO-OP Code': 'co_op_code',
#     'School Type': 'school_type',
#     'Grade': 'grade',
#     'Demographic': 'demographic',
#     'Suppressed': 'suppressed',
#     'Chronically Absent Students': 'chronically_absent_students',
#     'Students Enrolled 10 or More Days': 'students_enrolled_10_or_more_days',
#     'Chronic Absenteeism Rate': 'chronic_absenteeism_rate'

#  absenteeism_id BIGINT AUTO_INCREMENT PRIMARY KEY,
#  school_year CHAR(8) NOT NULL,
#  school_code VARCHAR(10) NOT NULL,
#  demographic VARCHAR(50) NOT NULL,
#  grade_level VARCHAR(50) NOT NULL,
#  suppressed VARCHAR(10),
#  chronically_absent_students INT,
#  enrolled_10_plus_days INT,
#  chronic_absenteeism_rate DECIMAL(8, 2),


ky_school_chron_abs_df = (chronic_absenteeism_df[['school_year', 'school_code', 'demographic', 'grade', 'suppressed', 'chronically_absent_students', 'students_enrolled_10_or_more_days', 'chronic_absenteeism_rate']])
ky_school_chron_abs_df.head()

,school_year,school_code,demographic,grade,suppressed,chronically_absent_students,students_enrolled_10_or_more_days,chronic_absenteeism_rate
0,20232024,999000,All Students,All Grades,No,"186,415","664,910",28
1,20232024,999000,Female,All Grades,No,"91,571","321,064",28.5
2,20232024,999000,Male,All Grades,No,"94,844","343,846",27.6
3,20232024,999000,African American,All Grades,No,"25,283","73,438",34.4
4,20232024,999000,American Indian or Alaska Native,All Grades,No,290,962,30.1

In [555]:
# dropout_rate_df = dropout_rate_df.rename(columns={
#     'School Year': 'school_year',
#     'County Number': 'county_number',
#     'County Name': 'county_name',
#     'District Number': 'district_number',
#     'District Name': 'district_name',
#     'School Number': 'school_number',
#     'School Name': 'school_name',
#     'School Code': 'school_code',
#     'State School Id': 'state_school_id',
#     'NCES ID': 'nces_id',
#     'CO-OP': 'co_op',
#     'CO-OP Code': 'co_op_code',
#     'School Type': 'school_type',
#     'Demographic': 'demographic',
#     'Suppressed': 'suppressed',
#     'Dropout Rate': 'dropout_rate',
# })

#  dropout_id BIGINT AUTO_INCREMENT PRIMARY KEY,
#  school_year CHAR(8) NOT NULL,
#  school_code VARCHAR(10) NOT NULL,
#  demographic VARCHAR(50) NOT NULL,
#  suppressed VARCHAR(10),
#  dropout_rate DECIMAL(8, 2),

ky_school_dropout_rate = (dropout_rate_df[['school_year', 'school_code', 'demographic', 'suppressed', 'dropout_rate']])
ky_school_dropout_rate.head()

,school_year,school_code,demographic,suppressed,dropout_rate
0,20232024,999000,All Students,N,1.3
1,20232024,999000,Female,N,1.1
2,20232024,999000,Male,N,1.5
3,20232024,999000,African American,N,2.2
4,20232024,999000,American Indian or Alaska Native,N,2.2