# Kentucky School Initial Data Review

The goal for this project is to see if there is a correlation between absenteeism and dropout rate. I've decided first to look at the absenteeism data from 2024-2025 and then I will continue on and look at the dropout rate.

Libraries and Parameters

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

seaborn.set_theme(style='whitegrid')

## KY School Data (2023-2025)

In [2]:
enrollment_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Student_Enrollment.csv")
enrollment_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Student_Enrollment.csv")

absenteeism_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Chronic_Absenteeism.csv")
absenteeism_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Chronic_Absenteeism.csv")

dropout_2023_2024_df = pd.read_csv("../Dataset/KYRC24_OVW_Dropout_Rate.csv")
dropout_2024_2025_df = pd.read_csv("../Dataset/KYRC25_OVW_Dropout_Rate.csv")


enrollment_df = pd.concat([enrollment_2023_2024_df, enrollment_2024_2025_df], ignore_index=True)
chronic_absenteeism_df = pd.concat([absenteeism_2023_2024_df, absenteeism_2024_2025_df], ignore_index=True)
dropout_rate_df = pd.concat([dropout_2023_2024_df, dropout_2024_2025_df], ignore_index=True)

## Initial Dataset Review

In [3]:
enrollment_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,...,Grade 4,Grade 5,Grade 6,Grade 7,Grade 8,Grade 9,Grade 10,Grade 11,Grade 12,Grade 14
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"49,321","49,728","46,144","49,278","50,090","56,075","54,149","50,192","47,786",653.0
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"23,912","24,119","22,146","23,926","24,063","27,061","26,353","24,607","23,210",217.0
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"25,409","25,609","23,998","25,352","26,027","29,014","27,796","25,585","24,576",436.0
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,"5,279","5,381","4,763","5,474","5,541","6,605","6,294","5,566","5,059",103.0
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,...,84,68,59,59,72,79,66,78,68,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46223,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,1,3,6,11,NaN
46224,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,1,0,2,0,NaN
46225,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,1,1,0,0,3,2,4,NaN
46226,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,0,1,1,0,NaN
46227,20242025,106.0,SHELBY,531,Shelby County,25.0,Cultivate Virtual Learning Academy,531025,106531025.0,2.105320e+11,...,NaN,NaN,0,0,0,0,0,1,0,NaN

In [4]:
chronic_absenteeism_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Grade,Demographic,Suppressed,Chronically Absent Students,Students Enrolled 10 or More Days,Chronic Absenteeism Rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,All Students,No,"186,415","664,910",28
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Female,No,"91,571","321,064",28.5
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,Male,No,"94,844","343,846",27.6
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,African American,No,"25,283","73,438",34.4
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Grades,American Indian or Alaska Native,No,290,962,30.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543271,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Foster Care,Yes,*,*,*
543272,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Gifted and Talented,Yes,*,*,*
543273,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Homeless,Yes,*,*,*
543274,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Migrant,Yes,*,*,*
543275,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,14th,Military Dependent,Yes,*,*,*

In [5]:
dropout_rate_df

,School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Demographic,Suppressed,Unnamed: 15,Dropout Rate
0,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,All Students,N,1.3,NaN
1,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Female,N,1.1,NaN
2,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,Male,N,1.5,NaN
3,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,African American,N,2.2,NaN
4,20232024,NaN,NaN,999,All Districts,NaN,All Schools,999000,NaN,NaN,NaN,NaN,NaN,American Indian or Alaska Native,N,2.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24529,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Student without Disabilities (IEP),N,NaN,0
24530,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,English Learner,Y,NaN,*
24531,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Non English Learner,N,NaN,0
24532,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Homeless,NaN,NaN,
24533,20242025,73.0,MADISON,606,Model Laboratory Schools at EKU,460.0,Model High School,606460,73606460.0,2.100290e+11,NaN,NaN,B1,Migrant,NaN,NaN,

## Analyzing the Data

## Data Cleanup

## Visual Analysis and Discovery

# Visualizations and Analysis

## Key Findings for Absenteeism

## What I've learned!